# Generated by Django 5.2.6 on 2025-09-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='manager',
            fields=[
                ('manager_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('manager_name', models.CharField(max_length=200)),
            ],
        ),
    ]
