# Generated by Django 5.2.6 on 2025-09-24 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_tester_delete_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tester',
        ),
    ]
