# Generated by Django 5.2.6 on 2025-09-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0003_delete_tester'),
    ]

    operations = [
        migrations.CreateModel(
            name='tester',
            fields=[
                ('manager_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('manager_name', models.CharField(max_length=200)),
                ('manager_salary', models.IntegerField(default=0)),
            ],
        ),
    ]
