# Generated by Django 5.2.6 on 2025-09-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('manager_name', models.CharField(max_length=200)),
                ('manager_salary', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='tester',
        ),
    ]
